### ISSUE TITLE
Timestamp für Gesten

### ISSUE THREAD

**Issue by Scarysize** [Scarysize/TwitchBox#10]
Es wäre sinnvoll wenn wir die Gestendaten jeweils timestampen bei jedem Schritt. Dass am Browser quasi dann irgendwann eine Geste ankommt mit:

- RecordedTime (Python)
- RecognizedTime (C++)
- ForwardedTime (NodeJS)

Dann kann man schnell nachvollziehen wo ein hoher Delay war.

**Comment by MarianBecher** [comment]
Python und C++ done

**Comment by Scarysize** [comment]
Dann machen wir hier zu.
