### ISSUE TITLE
Preview bei `componentWillReceiveProps`

### ISSUE THREAD

**Issue by Scarysize** [Scarysize/TwitchBox#13]
Wenn ein neues NavigationItem ausgewählt wird und die Preview wechselt (sprich neue Daten entsprechend der Auswahl abruft) sollten wir die "alten" PreviewDaten direkt verstecken.

Siehe auch: https://facebook.github.io/react/docs/component-specs.html#updating-componentwillreceiveprops

Ich glaube es sollte reichen die PreviewItems via CSS zu verstecken und wenn die Daten vom der API da sind wieder einzublenden.

**Comment by MarianBecher** [comment]
Und am besten beim verstecken via CSS ein loading GIF anzeigen

**Comment by Scarysize** [comment]
Loading CSS Animation bitte... 21. Jahrhundert und so
